import { Building2, BriefcaseBusiness, CircleHelp, Landmark, UserRound } from 'lucide-react';
import { Seo } from '../components/seo/Seo';
import { Button } from '../components/ui/Button';
import { FAQ } from '../components/ui/FAQ';
import { SectionHeading } from '../components/ui/SectionHeading';
import { Timeline } from '../components/ui/Timeline';

const profiles = [
  { icon: Building2, title: 'Je représente une entreprise', body: 'Votre OPCO et votre plan de développement des compétences sont les premières pistes à étudier selon le projet, le public et la formation retenue.', tags: ['OPCO', 'Plan de développement des compétences'] },
  { icon: UserRound, title: 'Je suis salarié', body: 'Le CPF peut être étudié lorsque la formation y est éligible. Selon votre situation, votre employeur ou son OPCO peuvent aussi être concernés.', tags: ['CPF si éligible', 'Employeur / OPCO'] },
  { icon: BriefcaseBusiness, title: 'Je suis demandeur d’emploi', body: 'France Travail, le CPF lorsque l’éligibilité est confirmée et d’autres dispositifs peuvent être étudiés en fonction de votre projet.', tags: ['France Travail', 'CPF si éligible'] },
];

const steps = [
  { title: 'Parler de votre situation', detail: 'Statut, projet, formation envisagée et calendrier permettent d’identifier les options à examiner.' },
  { title: 'Vérifier ce qui s’applique', detail: 'Les règles d’éligibilité, les prises en charge possibles et les documents attendus sont vérifiés sans promesse hasardeuse.' },
  { title: 'Avancer avec un dossier clair', detail: 'Vous savez quelles démarches engager et à quel moment avant de confirmer votre inscription ou votre session entreprise.' },
];

const faq = [
  { question: 'Puis-je utiliser mon CPF ?', answer: 'Cela dépend de l’éligibilité effective de la formation. P2A vérifie avec vous ce qui peut être mobilisé avant de vous orienter.' },
  { question: 'Mon OPCO peut-il prendre en charge la formation ?', answer: 'C’est une piste à étudier pour les entreprises. Les critères dépendent de votre OPCO, de votre projet et de la formation concernée.' },
  { question: 'P2A finance-t-il directement la formation ?', answer: 'P2A ne remplace pas un financeur. L’équipe vous aide à comprendre les options qui correspondent à votre situation et les démarches à prévoir.' },
];

export function FundingPage() {
  return <><Seo title="Financer votre formation" description="Entreprise, salarié ou demandeur d’emploi : P2A Formation vous aide à identifier les possibilités de financement à étudier." />
    <section className="relative overflow-hidden bg-p2a-violet-soft px-5 py-16 lg:px-8 lg:py-24"><div className="absolute -right-40 -top-48 h-[36rem] w-[36rem] rounded-full bg-p2a-orange/20 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_.62fr] lg:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-p2a-orange">Financements</p><h1 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.96] tracking-[-.065em] sm:text-6xl lg:text-7xl">Financer son projet sans se perdre dans les dispositifs.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-p2a-muted">Les possibilités dépendent de votre situation et du parcours choisi. P2A vous aide à identifier les pistes utiles, clairement et sans vous promettre ce qui ne peut pas l’être.</p><div className="mt-9 flex flex-wrap gap-3"><Button to="/contact">Étudier ma situation</Button><Button to="/formations" variant="secondary">Trouver une formation</Button></div></div><aside className="rounded-[1.75rem] bg-p2a-ink p-7 text-white sm:p-8"><Landmark className="text-p2a-orange" /><h2 className="mt-7 text-2xl font-extrabold tracking-[-.045em]">Un financement se prépare.</h2><p className="mt-4 text-sm leading-6 text-white/72">Le bon réflexe : parler de votre projet avant de vous inscrire pour vérifier les options et les délais à prendre en compte.</p></aside></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="Votre situation" title="Commencez par l’option qui vous ressemble." body="Les financements ne sont pas les mêmes pour tous. Choisissez votre profil pour comprendre les pistes à examiner." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{profiles.map(({icon:Icon,title,body,tags})=><article className="rounded-[1.65rem] border border-p2a-line bg-white p-7 shadow-sm" key={title}><span className="grid h-11 w-11 place-items-center rounded-2xl bg-p2a-orange-soft text-p2a-orange"><Icon size={22}/></span><h2 className="mt-9 text-xl font-extrabold tracking-[-.035em]">{title}</h2><p className="mt-3 text-sm leading-6 text-p2a-muted">{body}</p><div className="mt-7 flex flex-wrap gap-2">{tags.map(tag=><span className="rounded-full bg-p2a-violet-soft px-3 py-1.5 text-xs font-extrabold text-p2a-violet" key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section className="bg-p2a-canvas px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><SectionHeading eyebrow="Une démarche simple" title="Trois étapes pour prendre une décision informée." body="Notre rôle est de vous orienter. Les décisions de prise en charge appartiennent ensuite aux organismes financeurs compétents." /><Button to="/contact" className="mt-8">Demander un échange</Button></div><div className="rounded-[1.75rem] border border-p2a-line bg-white p-7 sm:p-9"><Timeline items={steps}/></div></div></section>
    <section className="bg-p2a-ink px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-p2a-orange">La bonne information au bon moment</p><h2 className="mt-5 text-4xl font-extrabold leading-[1.05] tracking-[-.055em]">Vous n’avez pas à maîtriser tous les dispositifs pour commencer.</h2></div><div className="grid gap-5 sm:grid-cols-2">{[['Ce que P2A fait','Clarifier votre projet, votre formation et les pistes à vérifier.'],['Ce que le financeur décide','Confirmer l’éligibilité, le montant et les conditions de prise en charge.']].map(([title,body])=><div className="rounded-2xl border border-white/15 bg-white/10 p-6" key={title}><CircleHelp className="text-p2a-orange" size={22}/><h3 className="mt-8 font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{body}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.7fr_1.3fr] lg:px-8 lg:py-28"><SectionHeading eyebrow="Questions fréquentes" title="Éviter les mauvaises surprises avant de s’engager." body="Un cas particulier ? L’équipe P2A peut vous orienter vers le bon prochain pas."/><FAQ items={faq}/></section>
    <section className="bg-p2a-orange px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-p2a-ink/65">Un projet, une situation, une réponse à construire</p><h2 className="mt-4 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-.05em] text-p2a-ink">Parlons de votre formation avant de parler de financement.</h2></div><Button to="/contact" className="shrink-0 bg-p2a-ink text-white hover:bg-white hover:text-p2a-ink">Être recontacté</Button></div></section>
  </>;
}
