import { Award, Check, ChevronRight, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { trainings } from '../data/trainings';
import { homeHero } from '../content/hero';
import { TrainingCard } from '../components/training/TrainingCard';
import { Button } from '../components/ui/Button';
import { Hero } from '../components/ui/Hero';
import { SectionHeading } from '../components/ui/SectionHeading';
import { TrustStrip } from '../components/ui/TrustStrip';
import { Seo } from '../components/seo/Seo';
import { TrustNarrative } from '../components/home/TrustNarrative';

const domains = [{icon:ShieldCheck,title:'Prévention & sécurité',body:'Faire de la sécurité un réflexe collectif.'},{icon:HeartHandshake,title:'Santé & médico-social',body:'Des pratiques plus sûres au service du soin.'},{icon:Award,title:'Hygiène alimentaire',body:'Protéger vos équipes, vos clients et votre activité.'},{icon:Sparkles,title:'QVT & management',body:'Prévenir l’usure et renforcer les collectifs.'}];
export function HomePage() { return <><Seo title="Formation professionnelle à Carrières-sur-Seine" description="P2A Formation accompagne entreprises et professionnels avec des parcours concrets, certifiés et adaptés."/><Hero content={homeHero}/><TrustStrip/>
<TrustNarrative/>
<section className="mx-auto max-w-7xl px-5 py-22 lg:px-8 lg:py-28"><SectionHeading eyebrow="Nos expertises" title="Former mieux. Agir durablement." body="Des parcours pensés pour répondre aux besoins opérationnels des organisations comme aux évolutions professionnelles de chacun."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{domains.map(({icon:Icon,...d}) => <Link to="/formations" key={d.title} className="group rounded-[1.5rem] border border-p2a-line bg-white p-6 transition hover:border-p2a-violet hover:bg-p2a-violet hover:text-white"><Icon size={27} className="text-p2a-orange"/><h3 className="mt-10 text-lg font-extrabold tracking-[-.03em]">{d.title}</h3><p className="mt-2 text-sm leading-6 text-p2a-muted group-hover:text-white/70">{d.body}</p><ChevronRight className="mt-7 group-hover:translate-x-1 transition-transform"/></Link>)}</div></section>
<section className="bg-p2a-violet-soft px-5 py-22 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Catalogue" title="Des formations déjà choisies par les équipes."/><Button to="/formations" variant="secondary">Voir le catalogue</Button></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{trainings.map(training => <TrainingCard training={training} key={training.slug}/>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-12 px-5 py-22 lg:grid-cols-2 lg:px-8 lg:py-28"><div><SectionHeading eyebrow="Notre engagement qualité" title="La rigueur d’un cadre. La proximité d’un partenaire." body="La certification Qualiopi structure notre démarche : écoute des besoins, objectifs transparents, pédagogie adaptée et évaluation des acquis."/><Button to="/qualiopi" className="mt-8">Découvrir notre démarche</Button></div><div className="rounded-[2rem] bg-white p-7 ring-1 ring-p2a-line sm:p-9"><img className="h-24 w-full object-contain object-left" src="/qualiopi.jpg" alt="Certification Qualiopi délivrée par ICPF"/><div className="mt-10 grid gap-6">{['Une analyse de votre besoin en amont','Des modalités adaptées aux situations de handicap','Un suivi des acquis et de votre satisfaction'].map(item=><div className="flex gap-3" key={item}><Check className="mt-0.5 shrink-0 text-p2a-orange"/><p className="font-bold">{item}</p></div>)}</div></div></section>
<section className="bg-p2a-ink px-5 py-18 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-p2a-orange">Un projet de formation ?</p><h2 className="mt-4 max-w-2xl text-4xl font-extrabold leading-tight tracking-[-.05em]">Parlons de ce qui ferait vraiment progresser vos équipes.</h2></div><Button to="/contact" className="bg-p2a-orange text-p2a-ink hover:bg-white">Être recontacté</Button></div></section></>; }
