import { Award, Check, ChevronRight, GraduationCap, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { trainings } from '../data/trainings';
import { TrainingCard } from '../components/training/TrainingCard';
import { Button } from '../components/ui/Button';
import { SectionHeading } from '../components/ui/SectionHeading';
import { TrustStrip } from '../components/ui/TrustStrip';
import { Seo } from '../components/seo/Seo';

const domains = [{icon:ShieldCheck,title:'Prévention & sécurité',body:'Faire de la sécurité un réflexe collectif.'},{icon:HeartHandshake,title:'Santé & médico-social',body:'Des pratiques plus sûres au service du soin.'},{icon:Award,title:'Hygiène alimentaire',body:'Protéger vos équipes, vos clients et votre activité.'},{icon:Sparkles,title:'QVT & management',body:'Prévenir l’usure et renforcer les collectifs.'}];
export function HomePage() { return <><Seo title="Formation professionnelle à Carrières-sur-Seine" description="P2A Formation accompagne entreprises et professionnels avec des parcours concrets, certifiés et adaptés."/><section className="relative overflow-hidden px-5 pb-16 pt-16 sm:pt-24 lg:px-8 lg:pb-28"><div className="absolute right-[-16rem] top-[-12rem] h-[38rem] w-[38rem] rounded-full bg-p2a-violet-soft blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.55}}><p className="mb-6 inline-flex items-center gap-2 rounded-full border border-p2a-line bg-white px-4 py-2 text-xs font-bold text-p2a-muted"><span className="h-2 w-2 rounded-full bg-p2a-orange"/> Organisme de formation certifié Qualiopi</p><h1 className="max-w-3xl text-5xl font-extrabold leading-[.96] tracking-[-.07em] sm:text-6xl lg:text-7xl">Faire grandir les <span className="text-p2a-violet">compétences</span> qui font avancer vos équipes.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-p2a-muted">P2A Formation conçoit des parcours concrets, exigeants et humains pour sécuriser les pratiques et accompagner vos transformations.</p><div className="mt-8 flex flex-wrap gap-3"><Button to="/formations">Explorer les formations</Button><Button to="/contact" variant="secondary">Construire un parcours</Button></div></motion.div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.6,delay:.1}} className="rounded-[2rem] bg-p2a-ink p-7 text-white shadow-2xl sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.17em] text-p2a-orange">Une formation qui se transforme en action</p><blockquote className="mt-10 text-2xl font-bold leading-tight tracking-[-.04em] sm:text-3xl">“Chaque parcours est ancré dans vos réalités de terrain, pour que l’apprentissage soit immédiatement utile.”</blockquote><div className="mt-10 flex items-center gap-4 border-t border-white/15 pt-6"><div className="grid h-12 w-12 place-items-center rounded-full bg-p2a-orange text-p2a-ink"><GraduationCap/></div><p className="text-sm text-white/70">Intra-entreprise, inter-entreprises<br/><span className="font-bold text-white">et parcours sur mesure</span></p></div></motion.div></div></section><TrustStrip/>
<section className="border-y border-p2a-line bg-white px-5 py-10 lg:px-8"><div className="mx-auto grid max-w-7xl gap-7 sm:grid-cols-3"><div><b className="text-2xl tracking-tight">Qualiopi</b><p className="mt-1 text-sm text-p2a-muted">Actions de formation & bilans de compétences</p></div><div><b className="text-2xl tracking-tight">Terrain</b><p className="mt-1 text-sm text-p2a-muted">Des outils transférables dès le lendemain</p></div><div><b className="text-2xl tracking-tight">Sur mesure</b><p className="mt-1 text-sm text-p2a-muted">Formats et contenus adaptés à votre organisation</p></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-22 lg:px-8 lg:py-28"><SectionHeading eyebrow="Nos expertises" title="Former mieux. Agir durablement." body="Des parcours pensés pour répondre aux besoins opérationnels des organisations comme aux évolutions professionnelles de chacun."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{domains.map(({icon:Icon,...d}) => <Link to="/formations" key={d.title} className="group rounded-[1.5rem] border border-p2a-line bg-white p-6 transition hover:border-p2a-violet hover:bg-p2a-violet hover:text-white"><Icon size={27} className="text-p2a-orange"/><h3 className="mt-10 text-lg font-extrabold tracking-[-.03em]">{d.title}</h3><p className="mt-2 text-sm leading-6 text-p2a-muted group-hover:text-white/70">{d.body}</p><ChevronRight className="mt-7 group-hover:translate-x-1 transition-transform"/></Link>)}</div></section>
<section className="bg-p2a-violet-soft px-5 py-22 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Catalogue" title="Des formations déjà choisies par les équipes."/><Button to="/formations" variant="secondary">Voir le catalogue</Button></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{trainings.map(training => <TrainingCard training={training} key={training.slug}/>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-12 px-5 py-22 lg:grid-cols-2 lg:px-8 lg:py-28"><div><SectionHeading eyebrow="Notre engagement qualité" title="La rigueur d’un cadre. La proximité d’un partenaire." body="La certification Qualiopi structure notre démarche : écoute des besoins, objectifs transparents, pédagogie adaptée et évaluation des acquis."/><Button to="/qualiopi" className="mt-8">Découvrir notre démarche</Button></div><div className="rounded-[2rem] bg-white p-7 ring-1 ring-p2a-line sm:p-9"><img className="h-24 w-full object-contain object-left" src="/qualiopi.jpg" alt="Certification Qualiopi délivrée par ICPF"/><div className="mt-10 grid gap-6">{['Une analyse de votre besoin en amont','Des modalités adaptées aux situations de handicap','Un suivi des acquis et de votre satisfaction'].map(item=><div className="flex gap-3" key={item}><Check className="mt-0.5 shrink-0 text-p2a-orange"/><p className="font-bold">{item}</p></div>)}</div></div></section>
<section className="bg-p2a-ink px-5 py-18 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-p2a-orange">Un projet de formation ?</p><h2 className="mt-4 max-w-2xl text-4xl font-extrabold leading-tight tracking-[-.05em]">Parlons de ce qui ferait vraiment progresser vos équipes.</h2></div><Button to="/contact" className="bg-p2a-orange text-p2a-ink hover:bg-white">Être recontacté</Button></div></section></>; }
